name: CI
on: [push]
jobs:
  tailwindcss-update:
    name: Generate Tailwind CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: assets/tailwind.input.css
          output: assets/tailwind.output.css
          params: ""
      - name: Commit & Push
        run: |
          git add --force assets/tailwind.output.css
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -m "ci: tailwindcss-update"
          git push
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
          lhci_min_score_performance: 0.8
          lhci_min_score_accessibility: 0.8
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}